({
    baseUrl: '/Users/filip/Sites/Ayurveda/public_html/js',
    paths: {
    	'jquery': 'vendor/jquery.min',
        'underscore': 'vendor/underscore',
        'backbone': 'vendor/backbone',
        'layoutmanager': 'vendor/backbone.layoutmanager',
        'handlebars': 'vendor/handlebars-1.3',
        'text': 'vendor/text',
        'async': 'vendor/async', 
        'noext': 'vendor/noext',
        "imagesLoaded": "libs/jquery.imagesloaded",
        'bootstrap': 'vendor/sass-bootstrap.min',
        'smartresize': 'libs/smartresize',
        'tweenmax': "libs/TweenMax.min",
        'gsap': "libs/jquery.gsap.min",        
        'imgLiquid' : 'libs/imgLiquid-min',
        'modernizr' : 'vendor/modernizr',
        'backstretch' : 'libs/jquery.backstretch.min',
        'nicescroll' : 'libs/jquery.nicescroll.min',
        'fittext' : 'libs/jquery.fittext',
        'fastclick': 'libs/fastclick',
        'pxloader': 'libs/pxloader/pxloader',
        'pxloadertags': 'libs/pxloader/pxloadertags',
        'pxloaderimage': 'libs/pxloader/pxloaderimage',
        'pxloadervideo': 'libs/pxloader/pxloadervideo',
        'stackblur': 'libs/StackBlur',
        'hoverDir': 'libs/jquery.hoverdir',
        'fastblur': 'libs/FastBlur'
    },
    name: "load",
    preserveLicenseComments: false,
    out: "app.min.js"
})